"""Additional central-government scheme records used by the PS16 demo catalog.

These are deliberately conservative prototype records.  The linked official
portal remains the source of truth for current rules, documents, and deadlines.
"""
from typing import List

from .models import Scheme


CATALOG_VERSION = "v2026.2-PS16"
VERIFIED_ON = "2026-09-12"
DEMO_NOTE = "Prototype catalog record. Verify the current rules and application window on the official portal before filing."


def central(
    *,
    id: str,
    name: str,
    short_name: str,
    ministry: str,
    category: str,
    tagline: str,
    description: str,
    amount: float,
    frequency: str,
    display_amount: str,
    documents: List[str],
    source: str,
    conflicts: List[str] | None = None,
) -> Scheme:
    return Scheme(
        id=id,
        name=name,
        shortName=short_name,
        ministry=ministry,
        level="Central",
        category=category,
        tagline=tagline,
        description=description,
        benefit={
            "type": "Government benefit or support",
            "amount": amount,
            "frequency": frequency,
            "displayAmount": display_amount,
        },
        applicableStates=["All States"],
        requiredDocuments=documents,
        officialSourceUrl=source,
        lastVerifiedDate=VERIFIED_ON,
        kbVersion=CATALOG_VERSION,
        validityNote=DEMO_NOTE,
        conflictingSchemeIds=conflicts or [],
    )


def build_additional_catalog() -> List[Scheme]:
    return [
        central(
            id="pm_kusum",
            name="PM-KUSUM",
            short_name="PM-KUSUM",
            ministry="Ministry of New and Renewable Energy",
            category="Agriculture",
            tagline="Support for solar pumps and renewable energy in agriculture",
            description="A prototype record for farmer and agricultural-land based renewable-energy support.",
            amount=100000.0,
            frequency="One-Time Subsidy",
            display_amount="Capital subsidy support",
            documents=["aadhaar", "land_712", "bank_passbook"],
            source="https://pmkusum.mnre.gov.in/",
        ),
        central(
            id="pm_surya_ghar",
            name="PM Surya Ghar: Muft Bijli Yojana",
            short_name="PM Surya Ghar",
            ministry="Ministry of New and Renewable Energy",
            category="Housing",
            tagline="Residential rooftop solar subsidy support",
            description="A prototype record for households applying for residential rooftop solar support.",
            amount=78000.0,
            frequency="One-Time Subsidy",
            display_amount="Up to INR 78,000 subsidy",
            documents=["aadhaar", "bank_passbook"],
            source="https://pmsuryaghar.gov.in/",
        ),
        central(
            id="kisan_credit_card",
            name="Kisan Credit Card",
            short_name="KCC",
            ministry="Ministry of Agriculture & Farmers Welfare",
            category="Agriculture",
            tagline="Timely institutional credit for farming and allied activities",
            description="A prototype record for farmers seeking formal short-term agricultural credit.",
            amount=300000.0,
            frequency="Credit Limit",
            display_amount="Credit access up to scheme limit",
            documents=["aadhaar", "land_712", "bank_passbook"],
            source="https://www.myscheme.gov.in/schemes/kcc",
        ),
        central(
            id="soil_health_card",
            name="Soil Health Card Scheme",
            short_name="Soil Health Card",
            ministry="Ministry of Agriculture & Farmers Welfare",
            category="Agriculture",
            tagline="Soil testing and nutrient recommendations for farmers",
            description="A prototype record for farmer-facing soil testing and crop nutrient guidance.",
            amount=0.0,
            frequency="Non-Monetary",
            display_amount="Soil test and advisory support",
            documents=["aadhaar", "land_712"],
            source="https://soilhealth.dac.gov.in/",
        ),
        central(
            id="pm_vishwakarma",
            name="PM Vishwakarma",
            short_name="PM Vishwakarma",
            ministry="Ministry of Micro, Small & Medium Enterprises",
            category="Business & Enterprise",
            tagline="Skill, toolkit, credit and marketing support for traditional artisans",
            description="A prototype record for eligible traditional artisans and craftspeople.",
            amount=150000.0,
            frequency="Training and Credit",
            display_amount="Training, toolkit and credit support",
            documents=["aadhaar", "bank_passbook"],
            source="https://pmvishwakarma.gov.in/",
        ),
        central(
            id="pmkvy",
            name="Pradhan Mantri Kaushal Vikas Yojana",
            short_name="PMKVY",
            ministry="Ministry of Skill Development & Entrepreneurship",
            category="Education",
            tagline="Short-term skill training and certification",
            description="A prototype record for citizens seeking government-supported skill training.",
            amount=0.0,
            frequency="Non-Monetary",
            display_amount="Training and certification support",
            documents=["aadhaar", "bank_passbook"],
            source="https://www.skillindiadigital.gov.in/",
        ),
        central(
            id="pmay_urban",
            name="Pradhan Mantri Awas Yojana - Urban",
            short_name="PMAY-U",
            ministry="Ministry of Housing and Urban Affairs",
            category="Housing",
            tagline="Housing support for eligible urban households",
            description="A prototype record for eligible urban and semi-urban households seeking housing assistance.",
            amount=250000.0,
            frequency="Housing Assistance",
            display_amount="Housing assistance as per component",
            documents=["aadhaar", "income_cert", "bank_passbook"],
            source="https://pmaymis.gov.in/",
        ),
        central(
            id="pm_ujjwala",
            name="Pradhan Mantri Ujjwala Yojana",
            short_name="PMUY",
            ministry="Ministry of Petroleum and Natural Gas",
            category="Women & Child Welfare",
            tagline="Clean cooking connection support for eligible women",
            description="A prototype record for women in eligible low-income households seeking LPG connection support.",
            amount=1600.0,
            frequency="One-Time Support",
            display_amount="Connection support as per scheme rules",
            documents=["aadhaar", "ration_card", "bank_passbook"],
            source="https://www.pmuy.gov.in/",
        ),
        central(
            id="pm_jan_dhan",
            name="Pradhan Mantri Jan-Dhan Yojana",
            short_name="PMJDY",
            ministry="Department of Financial Services",
            category="Health & Social Security",
            tagline="Basic bank account and financial inclusion services",
            description="A prototype record for citizens seeking access to basic banking and financial inclusion services.",
            amount=0.0,
            frequency="Non-Monetary",
            display_amount="Basic banking access and services",
            documents=["aadhaar"],
            source="https://www.pmjdy.gov.in/",
        ),
        central(
            id="pmjjby",
            name="Pradhan Mantri Jeevan Jyoti Bima Yojana",
            short_name="PMJJBY",
            ministry="Department of Financial Services",
            category="Health & Social Security",
            tagline="Low-cost life insurance cover through a bank account",
            description="A prototype record for eligible account holders seeking life insurance cover.",
            amount=200000.0,
            frequency="Insurance Cover",
            display_amount="Life cover as per current rules",
            documents=["aadhaar", "bank_passbook"],
            source="https://www.jansuraksha.gov.in/",
        ),
        central(
            id="pmsby",
            name="Pradhan Mantri Suraksha Bima Yojana",
            short_name="PMSBY",
            ministry="Department of Financial Services",
            category="Health & Social Security",
            tagline="Low-cost accident insurance cover",
            description="A prototype record for eligible account holders seeking accident insurance cover.",
            amount=200000.0,
            frequency="Insurance Cover",
            display_amount="Accident cover as per current rules",
            documents=["aadhaar", "bank_passbook"],
            source="https://www.jansuraksha.gov.in/",
        ),
        central(
            id="nsap",
            name="National Social Assistance Programme",
            short_name="NSAP",
            ministry="Ministry of Rural Development",
            category="Health & Social Security",
            tagline="Social assistance for eligible vulnerable households",
            description="A prototype record for age and household-support based social assistance screening.",
            amount=12000.0,
            frequency="Annual Support",
            display_amount="Pension/support as per component",
            documents=["aadhaar", "ration_card", "bank_passbook"],
            source="https://nsap.nic.in/",
        ),
        central(
            id="pm_matru_vandana",
            name="Pradhan Mantri Matru Vandana Yojana",
            short_name="PMMVY",
            ministry="Ministry of Women and Child Development",
            category="Women & Child Welfare",
            tagline="Maternity benefit support for eligible women",
            description="A prototype record for maternity benefit screening and application guidance.",
            amount=11000.0,
            frequency="Maternity Benefit",
            display_amount="Maternity benefit as per current rules",
            documents=["aadhaar", "bank_passbook"],
            source="https://wcd.gov.in/schemes/pradhan-mantri-matru-vandana-yojana",
        ),
        central(
            id="eshram",
            name="e-Shram",
            short_name="e-Shram",
            ministry="Ministry of Labour & Employment",
            category="Health & Social Security",
            tagline="National registration and support access for unorganised workers",
            description="A prototype record for unorganised workers seeking a portable registration record.",
            amount=0.0,
            frequency="Non-Monetary",
            display_amount="Worker registration and service access",
            documents=["aadhaar", "bank_passbook"],
            source="https://eshram.gov.in/",
        ),
        central(
            id="nrlm",
            name="Deendayal Antyodaya Yojana - National Rural Livelihoods Mission",
            short_name="DAY-NRLM",
            ministry="Ministry of Rural Development",
            category="Women & Child Welfare",
            tagline="Women-led rural self-help group livelihood support",
            description="A prototype record for rural women seeking self-help group livelihood support.",
            amount=50000.0,
            frequency="Livelihood Support",
            display_amount="Group and livelihood support",
            documents=["aadhaar", "bank_passbook"],
            source="https://aajeevika.gov.in/",
        ),
        central(
            id="pmfme",
            name="PM Formalisation of Micro Food Processing Enterprises",
            short_name="PMFME",
            ministry="Ministry of Food Processing Industries",
            category="Business & Enterprise",
            tagline="Credit-linked support for micro food-processing enterprises",
            description="A prototype record for existing or proposed micro food-processing entrepreneurs.",
            amount=400000.0,
            frequency="Credit-Linked Support",
            display_amount="Credit-linked subsidy as per current rules",
            documents=["aadhaar", "bank_passbook", "income_cert"],
            source="https://pmfme.mofpi.gov.in/",
        ),
        central(
            id="central_sector_scholarship",
            name="Central Sector Scheme of Scholarship for College and University Students",
            short_name="Central Sector Scholarship",
            ministry="Ministry of Education",
            category="Education",
            tagline="Higher-education scholarship for eligible students",
            description="A prototype record for students seeking merit and means-based scholarship screening.",
            amount=20000.0,
            frequency="Annual Scholarship",
            display_amount="Scholarship as per course level",
            documents=["aadhaar", "income_cert", "student_id_bonafide"],
            source="https://scholarships.gov.in/",
            conflicts=["post_matric_scholarship", "state_higher_ed_stipend"],
        ),
        central(
            id="top_class_education_sc",
            name="Top Class Education Scheme for SC Students",
            short_name="Top Class SC Education",
            ministry="Ministry of Social Justice & Empowerment",
            category="Education",
            tagline="Higher-education support for eligible SC students",
            description="A prototype record for SC students in notified institutions or courses.",
            amount=86000.0,
            frequency="Annual Scholarship",
            display_amount="Tuition and maintenance support",
            documents=["aadhaar", "caste_cert", "income_cert", "student_id_bonafide"],
            source="https://scholarships.gov.in/",
            conflicts=["post_matric_scholarship", "central_sector_scholarship"],
        ),
        central(
            id="post_matric_obc",
            name="Post-Matric Scholarship for OBC Students",
            short_name="Post-Matric OBC",
            ministry="Ministry of Social Justice & Empowerment",
            category="Education",
            tagline="Post-matric scholarship support for eligible OBC students",
            description="A prototype record for OBC students seeking post-matric scholarship screening.",
            amount=42000.0,
            frequency="Annual Scholarship",
            display_amount="Fee and maintenance support",
            documents=["aadhaar", "caste_cert", "income_cert", "student_id_bonafide"],
            source="https://scholarships.gov.in/",
            conflicts=["post_matric_scholarship", "central_sector_scholarship"],
        ),
        central(
            id="national_overseas_scholarship",
            name="National Overseas Scholarship",
            short_name="National Overseas Scholarship",
            ministry="Ministry of Social Justice & Empowerment",
            category="Education",
            tagline="Financial support for eligible students studying abroad",
            description="A prototype record for SC/ST students considering higher studies abroad.",
            amount=800000.0,
            frequency="Annual Scholarship",
            display_amount="Overseas study support as per rules",
            documents=["aadhaar", "caste_cert", "income_cert", "student_id_bonafide"],
            source="https://socialjustice.gov.in/schemes",
        ),
        central(
            id="pm_daksh",
            name="PM-DAKSH",
            short_name="PM-DAKSH",
            ministry="Ministry of Social Justice & Empowerment",
            category="Education",
            tagline="Skill training for disadvantaged groups",
            description="A prototype record for skill training and livelihood preparation screening.",
            amount=0.0,
            frequency="Non-Monetary",
            display_amount="Training and livelihood support",
            documents=["aadhaar", "caste_cert"],
            source="https://pmdaksh.dosje.gov.in/",
        ),
        central(
            id="pm_krishi_sinchayee",
            name="Pradhan Mantri Krishi Sinchayee Yojana",
            short_name="PMKSY",
            ministry="Ministry of Agriculture & Farmers Welfare",
            category="Agriculture",
            tagline="Irrigation and water-use efficiency support",
            description="A prototype record for farmers seeking irrigation and water-use efficiency support.",
            amount=100000.0,
            frequency="Project Support",
            display_amount="Irrigation support as per component",
            documents=["aadhaar", "land_712", "bank_passbook"],
            source="https://pmksy.gov.in/",
        ),
        central(
            id="pmfby",
            name="Pradhan Mantri Fasal Bima Yojana",
            short_name="PMFBY",
            ministry="Ministry of Agriculture & Farmers Welfare",
            category="Agriculture",
            tagline="Crop insurance support against notified losses",
            description="A prototype record for farmers checking crop-insurance enrollment and claim guidance.",
            amount=0.0,
            frequency="Insurance Cover",
            display_amount="Crop insurance as per notified terms",
            documents=["aadhaar", "land_712", "bank_passbook"],
            source="https://pmfby.gov.in/farmerApplicationLogin",
        ),
        central(
            id="pm_egp",
            name="Prime Minister's Employment Generation Programme",
            short_name="PMEGP",
            ministry="Ministry of Micro, Small & Medium Enterprises",
            category="Business & Enterprise",
            tagline="Credit-linked subsidy for new micro enterprises",
            description="A prototype record for citizens planning a new micro-enterprise.",
            amount=250000.0,
            frequency="Credit-Linked Subsidy",
            display_amount="Subsidy support as per project category",
            documents=["aadhaar", "bank_passbook", "income_cert"],
            source="https://pmegp.msme.gov.in/Home/Index",
        ),
        central(
            id="sukanya_samriddhi",
            name="Sukanya Samriddhi Account",
            short_name="Sukanya Samriddhi",
            ministry="Ministry of Finance",
            category="Women & Child Welfare",
            tagline="Long-term savings account for a girl child",
            description="A prototype record for families seeking girl-child savings account information.",
            amount=0.0,
            frequency="Savings Account",
            display_amount="Government savings product",
            documents=["aadhaar", "bank_passbook"],
            source="https://www.indiapost.gov.in/Financial/DOP_PDFFiles/SSA.pdf",
        ),
        central(
            id="national_apprenticeship",
            name="National Apprenticeship Promotion Scheme",
            short_name="NAPS",
            ministry="Ministry of Skill Development & Entrepreneurship",
            category="Education",
            tagline="Apprenticeship opportunities with employer support",
            description="A prototype record for students and job seekers exploring apprenticeship opportunities.",
            amount=1500.0,
            frequency="Monthly Support",
            display_amount="Apprenticeship support as per current rules",
            documents=["aadhaar", "student_id_bonafide"],
            source="https://www.apprenticeshipindia.gov.in/",
        ),
        central(
            id="deendayal_upadhyaya_gky",
            name="Deen Dayal Upadhyaya Grameen Kaushalya Yojana",
            short_name="DDU-GKY",
            ministry="Ministry of Rural Development",
            category="Education",
            tagline="Placement-linked skill training for rural youth",
            description="A prototype record for rural youth seeking placement-linked skill training.",
            amount=0.0,
            frequency="Non-Monetary",
            display_amount="Training and placement support",
            documents=["aadhaar", "domicile_cert"],
            source="https://ddugky.info/",
        ),
    ]
