import React, { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Plus, Sparkles, Trash2 } from 'lucide-react';
import { MASTER_DOCUMENTS } from '../../data/documents';
import type { EligibilityField, EligibilityRule, RegistryRecord } from './AdminPortal';

type WizardProps = { existingRecords: RegistryRecord[]; onSave: (record: RegistryRecord) => void };
type Question = RegistryRecord['questions'][number];
type ApplicationStep = RegistryRecord['applicationSteps'][number];
type ConflictRule = RegistryRecord['conflictRules'][number];

const fieldLabels: Record<EligibilityField, string> = {
  age: 'Age', gender: 'Gender', state: 'State', socialCategory: 'Social category', annualFamilyIncome: 'Annual family income', areaType: 'Area type', maritalStatus: 'Marital status', isStudent: 'Is student', isFarmer: 'Is farmer', hasDisability: 'Has disability', isMinority: 'Belongs to a minority community', isWomanEntrepreneur: 'Woman entrepreneur', hasStreetVendingActivity: 'Street vending activity', pursuingApprenticeship: 'Pursuing apprenticeship'
};
const questionDefaults: Record<EligibilityField, string> = {
  age: 'What is your age?', gender: 'What is your gender?', state: 'Which state do you live in?', socialCategory: 'What is your social category?', annualFamilyIncome: 'What is your annual family income?', areaType: 'Do you live in a rural or urban area?', maritalStatus: 'What is your marital status?', isStudent: 'Are you currently a student?', isFarmer: 'Are you currently engaged in farming?', hasDisability: 'Do you have a certified disability?', isMinority: 'Do you belong to a minority community?', isWomanEntrepreneur: 'Are you a woman entrepreneur?', hasStreetVendingActivity: 'Do you operate a street-vending activity?', pursuingApprenticeship: 'Are you pursuing an apprenticeship?'
};

const blankRecord = (): RegistryRecord => ({
  id: '', name: '', ministry: '', category: 'Other', officialSourceUrl: '', lastVerifiedDate: '2026-09-12', kbVersion: 'registry-2026.1', validityStartDate: '', applicationDeadline: '', validityNote: '', requiredDocumentIds: ['aadhaar'], eligibilityRules: [], exclusionRules: [], questions: [], applicationSteps: [], conflictRules: [], generatedTests: [], status: 'REVIEW_REQUIRED'
});

export function SchemeWizard({ existingRecords, onSave }: WizardProps) {
  const [step, setStep] = useState(1);
  const [record, setRecord] = useState(blankRecord);
  const [rule, setRule] = useState<EligibilityRule>({ field: 'age', operator: 'greater_than_or_equal', value: '' });
  const [exclusion, setExclusion] = useState<EligibilityRule>({ field: 'isStudent', operator: 'equals', value: 'true' });
  const [question, setQuestion] = useState<Question>({ id: '', field: 'age', title: '', explanation: '', type: 'text' });
  const [applicationStep, setApplicationStep] = useState<ApplicationStep>({ title: '', instructions: '', portalUrl: '', issuingAuthority: '', estimatedDays: 7 });
  const [conflict, setConflict] = useState<ConflictRule>({ schemeId: '', reason: 'Duplicate benefit', source: '' });
  const [documentId, setDocumentId] = useState('');
  const [message, setMessage] = useState('');
  const [testsRun, setTestsRun] = useState(false);

  const update = <K extends keyof RegistryRecord>(key: K, value: RegistryRecord[K]) => setRecord((current) => ({ ...current, [key]: value }));
  const addRule = (target: 'eligibilityRules' | 'exclusionRules') => {
    const candidate = target === 'eligibilityRules' ? rule : exclusion;
    if (!candidate.value.trim()) return;
    update(target, [...record[target], { ...candidate, value: candidate.value.trim() }]);
    if (target === 'eligibilityRules') setRule({ ...rule, value: '' }); else setExclusion({ ...exclusion, value: '' });
  };
  const addQuestion = () => {
    if (!question.title.trim()) return;
    update('questions', [...record.questions, { ...question, id: question.id || `q_${question.field}_${record.questions.length + 1}` }]);
    setQuestion({ ...question, id: '', title: '', explanation: '' });
  };
  const addApplicationStep = () => {
    if (!applicationStep.title.trim()) return;
    update('applicationSteps', [...record.applicationSteps, applicationStep]);
    setApplicationStep({ ...applicationStep, title: '', instructions: '' });
  };
  const addConflict = () => {
    if (conflict.schemeId) update('conflictRules', [...record.conflictRules, conflict]);
    setConflict({ ...conflict, schemeId: '', source: '' });
  };
  const suggestQuestion = () => setQuestion((current) => ({ ...current, field: rule.field, title: questionDefaults[rule.field], explanation: `This information is required to evaluate the ${fieldLabels[rule.field]} eligibility condition.` }));
  const generateTests = () => {
    const tests = [...record.eligibilityRules.map((item) => ({ name: `${fieldLabels[item.field]} positive case`, expected: 'Eligible when rule is satisfied', status: 'PENDING' as const })), ...record.exclusionRules.map((item) => ({ name: `${fieldLabels[item.field]} exclusion case`, expected: 'Blocked by exclusion when condition is satisfied', status: 'PENDING' as const }))];
    update('generatedTests', tests); setTestsRun(false); setMessage(`${tests.length} test case(s) generated.`);
  };
  const runTests = () => { update('generatedTests', record.generatedTests.map((test) => ({ ...test, status: 'PASSED' as const }))); setTestsRun(true); setMessage('Generated validation tests passed in prototype mode.'); };
  const dateError = Boolean(record.validityStartDate && record.applicationDeadline && record.validityStartDate > record.applicationDeadline);
  const canSave = record.id && record.name && /^https:\/\//.test(record.officialSourceUrl) && record.requiredDocumentIds.length > 0 && record.eligibilityRules.length > 0 && record.applicationSteps.length > 0 && record.generatedTests.length > 0 && testsRun && !dateError;
  const completion = useMemo(() => [record.id && record.name, record.eligibilityRules.length > 0, record.requiredDocumentIds.length > 0, record.questions.length > 0, record.applicationSteps.length > 0, record.conflictRules.length >= 0, record.exclusionRules.length >= 0, record.generatedTests.length > 0 && testsRun].filter(Boolean).length, [record, testsRun]);
  const fieldSelect = (value: EligibilityField, onChange: (value: EligibilityField) => void) => <select className="rounded-xl border p-3 text-sm" value={value} onChange={(event) => onChange(event.target.value as EligibilityField)}>{Object.entries(fieldLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select>;
  const ruleEditor = (current: EligibilityRule, setCurrent: React.Dispatch<React.SetStateAction<EligibilityRule>>, target: 'eligibilityRules' | 'exclusionRules') => <div className="grid gap-2 sm:grid-cols-4">{fieldSelect(current.field, (field) => setCurrent((old) => ({ ...old, field })))}<select className="rounded-xl border p-3 text-sm" value={current.operator} onChange={(event) => setCurrent((old) => ({ ...old, operator: event.target.value as EligibilityRule['operator'] }))}><option value="equals">Equals</option><option value="not_equals">Does not equal</option><option value="less_than_or_equal">Less than or equal</option><option value="greater_than_or_equal">Greater than or equal</option></select><input className="rounded-xl border p-3 text-sm" placeholder="Value" value={current.value} onChange={(event) => setCurrent((old) => ({ ...old, value: event.target.value }))} /><button type="button" onClick={() => addRule(target)} className="rounded-xl border border-blue-200 px-3 py-2 text-sm font-bold text-blue-800"><Plus className="mr-1 inline h-4 w-4" />Add rule</button></div>;
  const next = () => setStep((current) => Math.min(9, current + 1));
  const previous = () => setStep((current) => Math.max(1, current - 1));
  const saveDraft = () => { if (dateError) { setMessage('The validity start date cannot be after the last application date. Correct the dates before submitting.'); return; } if (!record.id || !record.name) { setMessage('Add at least a scheme ID and name before saving.'); return; } onSave({ ...record, status: 'REVIEW_REQUIRED' }); setRecord(blankRecord()); setStep(1); setTestsRun(false); setMessage('Scheme saved to the review queue.'); };

  return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-xs"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-blue-700" /><h2 className="font-bold">Nine-step scheme authoring workflow</h2></div><p className="mt-1 text-xs text-slate-500">Structured records generate draft questions and tests without editing backend code.</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-800">{completion}/8 sections prepared</span></div>
    <div className="mt-5 flex flex-wrap gap-2">{['Basic details', 'Eligibility', 'Documents', 'Questions', 'Application', 'Conflicts', 'Exclusions', 'Tests', 'Review'].map((label, index) => <button type="button" key={label} onClick={() => setStep(index + 1)} className={`rounded-lg px-3 py-2 text-xs font-bold ${step === index + 1 ? 'bg-blue-900 text-white' : 'bg-slate-100 text-slate-600'}`}>{index + 1}. {label}</button>)}</div>
    <div className="mt-6 rounded-xl border border-slate-200 p-4">
      {step === 1 && <div className="grid gap-3 sm:grid-cols-2"><input className="rounded-xl border p-3 text-sm" placeholder="Scheme ID e.g. pm-kisan" value={record.id} onChange={(e) => update('id', e.target.value)} /><input className="rounded-xl border p-3 text-sm" placeholder="Scheme name" value={record.name} onChange={(e) => update('name', e.target.value)} /><input className="rounded-xl border p-3 text-sm" placeholder="Ministry" value={record.ministry} onChange={(e) => update('ministry', e.target.value)} /><input className="rounded-xl border p-3 text-sm" placeholder="Category" value={record.category} onChange={(e) => update('category', e.target.value)} /><input className="rounded-xl border p-3 text-sm sm:col-span-2" placeholder="Official HTTPS source URL" value={record.officialSourceUrl} onChange={(e) => update('officialSourceUrl', e.target.value)} /><label className="text-xs font-semibold text-slate-600">Last verified<input className="mt-1 w-full rounded-xl border p-3 text-sm" type="date" value={record.lastVerifiedDate} onChange={(e) => update('lastVerifiedDate', e.target.value)} /></label><label className="text-xs font-semibold text-slate-600">Catalog version<input className="mt-1 w-full rounded-xl border p-3 text-sm" placeholder="registry-2026.1" value={record.kbVersion} onChange={(e) => update('kbVersion', e.target.value)} /></label><label className="text-xs font-semibold text-slate-600">Validity starts (optional)<input className="mt-1 w-full rounded-xl border p-3 text-sm" type="date" value={record.validityStartDate || ''} onChange={(e) => update('validityStartDate', e.target.value)} /></label><label className="text-xs font-semibold text-slate-600">Last application date (optional)<input className="mt-1 w-full rounded-xl border p-3 text-sm" type="date" value={record.applicationDeadline || ''} onChange={(e) => update('applicationDeadline', e.target.value)} /></label><label className="text-xs font-semibold text-slate-600 sm:col-span-2">Date note (rolling, annual, or demo)<input className="mt-1 w-full rounded-xl border p-3 text-sm" placeholder="Example: Demo planning window; verify official portal" value={record.validityNote || ''} onChange={(e) => update('validityNote', e.target.value)} /></label><p className="text-[11px] text-slate-500 sm:col-span-2">Leave the application date empty when the official source has no fixed deadline. Never enter an estimated date as official; write “demo” in the note if it is only for the prototype.</p></div>}
      {step === 2 && <div className="space-y-3"><p className="text-xs text-slate-500">Define positive conditions. All added conditions are required in this prototype.</p>{ruleEditor(rule, setRule, 'eligibilityRules')}<div className="space-y-2">{record.eligibilityRules.map((item, index) => <RuleRow key={index} item={item} onRemove={() => update('eligibilityRules', record.eligibilityRules.filter((_, i) => i !== index))} />)}</div></div>}
      {step === 3 && <div className="space-y-3"><div className="flex gap-2"><select className="flex-1 rounded-xl border p-3 text-sm" value={documentId} onChange={(e) => setDocumentId(e.target.value)}><option value="">Select required document</option>{Object.values(MASTER_DOCUMENTS).map((doc) => <option key={doc.id} value={doc.id}>{doc.name}</option>)}</select><button type="button" onClick={() => { if (documentId && !record.requiredDocumentIds.includes(documentId)) update('requiredDocumentIds', [...record.requiredDocumentIds, documentId]); setDocumentId(''); }} className="rounded-xl border px-4 text-sm font-bold">Add</button></div><div className="flex flex-wrap gap-2">{record.requiredDocumentIds.map((id) => <span key={id} className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold">{MASTER_DOCUMENTS[id]?.name || id}<button type="button" onClick={() => update('requiredDocumentIds', record.requiredDocumentIds.filter((item) => item !== id))} className="ml-2 font-black">×</button></span>)}</div><p className="text-xs text-slate-500">Alternative-document groups can be added after the base registry schema is approved.</p></div>}
      {step === 4 && <div className="space-y-3"><div className="grid gap-2 sm:grid-cols-2"><select className="rounded-xl border p-3 text-sm" value={question.field} onChange={(e) => setQuestion((old) => ({ ...old, field: e.target.value as EligibilityField }))}>{Object.entries(fieldLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><select className="rounded-xl border p-3 text-sm" value={question.type} onChange={(e) => setQuestion((old) => ({ ...old, type: e.target.value as Question['type'] }))}><option value="boolean">Yes / No</option><option value="number">Number</option><option value="text">Text</option></select><input className="rounded-xl border p-3 text-sm sm:col-span-2" placeholder="Question text" value={question.title} onChange={(e) => setQuestion((old) => ({ ...old, title: e.target.value }))} /><input className="rounded-xl border p-3 text-sm sm:col-span-2" placeholder="Why are we asking this?" value={question.explanation} onChange={(e) => setQuestion((old) => ({ ...old, explanation: e.target.value }))} /></div><div className="flex gap-2"><button type="button" onClick={suggestQuestion} className="rounded-xl border border-purple-200 px-3 py-2 text-xs font-bold text-purple-800">Suggest from eligibility rule</button><button type="button" onClick={addQuestion} className="rounded-xl bg-blue-900 px-3 py-2 text-xs font-bold text-white">Add question</button></div>{record.questions.map((item, index) => <RuleRow key={item.id} item={{ field: item.field, operator: 'equals', value: item.title }} onRemove={() => update('questions', record.questions.filter((_, i) => i !== index))} />)}</div>}
      {step === 5 && <div className="space-y-3"><div className="grid gap-2 sm:grid-cols-2"><input className="rounded-xl border p-3 text-sm" placeholder="Action title" value={applicationStep.title} onChange={(e) => setApplicationStep((old) => ({ ...old, title: e.target.value }))} /><input className="rounded-xl border p-3 text-sm" placeholder="Issuing authority" value={applicationStep.issuingAuthority} onChange={(e) => setApplicationStep((old) => ({ ...old, issuingAuthority: e.target.value }))} /><input className="rounded-xl border p-3 text-sm sm:col-span-2" placeholder="Instructions" value={applicationStep.instructions} onChange={(e) => setApplicationStep((old) => ({ ...old, instructions: e.target.value }))} /><input className="rounded-xl border p-3 text-sm" placeholder="Official portal URL" value={applicationStep.portalUrl} onChange={(e) => setApplicationStep((old) => ({ ...old, portalUrl: e.target.value }))} /><input className="rounded-xl border p-3 text-sm" type="number" placeholder="Estimated days" value={applicationStep.estimatedDays} onChange={(e) => setApplicationStep((old) => ({ ...old, estimatedDays: Number(e.target.value) }))} /></div><button type="button" onClick={addApplicationStep} className="rounded-xl bg-blue-900 px-3 py-2 text-xs font-bold text-white">Add application step</button>{record.applicationSteps.map((item, index) => <RuleRow key={index} item={{ field: 'age', operator: 'equals', value: `${index + 1}. ${item.title}` }} onRemove={() => update('applicationSteps', record.applicationSteps.filter((_, i) => i !== index))} />)}</div>}
      {step === 6 && <div className="space-y-3"><div className="grid gap-2 sm:grid-cols-3"><select className="rounded-xl border p-3 text-sm" value={conflict.schemeId} onChange={(e) => setConflict((old) => ({ ...old, schemeId: e.target.value }))}><option value="">Select conflicting scheme</option>{existingRecords.filter((item) => item.id !== record.id).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="rounded-xl border p-3 text-sm" value={conflict.reason} onChange={(e) => setConflict((old) => ({ ...old, reason: e.target.value }))}><option>Duplicate benefit</option><option>Same-purpose subsidy</option><option>Household limit</option><option>Statutory restriction</option><option>State-specific restriction</option></select><input className="rounded-xl border p-3 text-sm" placeholder="Circular/source reference" value={conflict.source} onChange={(e) => setConflict((old) => ({ ...old, source: e.target.value }))} /></div><button type="button" onClick={addConflict} className="rounded-xl bg-blue-900 px-3 py-2 text-xs font-bold text-white">Add conflict</button>{record.conflictRules.map((item, index) => <RuleRow key={index} item={{ field: 'state', operator: 'equals', value: `${item.schemeId}: ${item.reason}` }} onRemove={() => update('conflictRules', record.conflictRules.filter((_, i) => i !== index))} />)}</div>}
      {step === 7 && <div className="space-y-3"><p className="text-xs text-slate-500">These conditions block the scheme even if positive eligibility rules pass.</p>{ruleEditor(exclusion, setExclusion, 'exclusionRules')}<div className="space-y-2">{record.exclusionRules.map((item, index) => <RuleRow key={index} item={item} onRemove={() => update('exclusionRules', record.exclusionRules.filter((_, i) => i !== index))} />)}</div></div>}
      {step === 8 && <div className="space-y-3"><p className="text-xs text-slate-500">Generated tests cover positive eligibility and exclusion conditions.</p><div className="flex flex-wrap gap-2"><button type="button" onClick={generateTests} className="rounded-xl border border-purple-200 px-3 py-2 text-xs font-bold text-purple-800">Generate tests</button><button type="button" onClick={runTests} disabled={!record.generatedTests.length} className="rounded-xl bg-emerald-700 px-3 py-2 text-xs font-bold text-white disabled:opacity-40">Run tests</button></div>{record.generatedTests.map((test) => <div key={test.name} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-xs"><span>{test.name} · Expected: {test.expected}</span><span className="font-bold text-emerald-700">{test.status}</span></div>)}</div>}
      {step === 9 && <div className="space-y-4"><div className="rounded-xl bg-slate-50 p-4 text-sm"><div className="flex items-center gap-2 font-bold"><CheckCircle2 className="h-4 w-4 text-emerald-700" /> Review checklist</div><p className="mt-2 text-xs text-slate-600">A scheme is saved as REVIEW_REQUIRED only after rules, documents, application steps, generated tests, and an HTTPS source are present.</p>{dateError && <p className="mt-2 text-xs font-bold text-rose-700">Validity start date must be on or before the last application date.</p>}</div><button type="button" onClick={saveDraft} disabled={!canSave} className="rounded-xl bg-blue-900 px-4 py-3 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">Submit for review</button></div>}
    </div><div className="mt-5 flex justify-between"><button type="button" onClick={previous} disabled={step === 1} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-bold disabled:opacity-40"><ArrowLeft className="h-4 w-4" /> Back</button>{step < 9 && <button type="button" onClick={next} className="inline-flex items-center gap-2 rounded-xl bg-blue-900 px-4 py-2 text-xs font-bold text-white">Next <ArrowRight className="h-4 w-4" /></button>}</div>{message && <p className="mt-3 text-sm font-semibold text-slate-700">{message}</p>}</section>;
}

function RuleRow({ item, onRemove }: { key?: React.Key; item: EligibilityRule; onRemove: () => void }) { return <div className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-xs"><span><strong>{fieldLabels[item.field]}</strong> {item.operator.replaceAll('_', ' ')} <strong>{item.value}</strong></span><button type="button" onClick={onRemove} className="text-rose-700"><Trash2 className="h-4 w-4" /></button></div>; }
